### ISSUE TITLE
Want to save this training weight

### ISSUE THREAD

**Issue by BeccaHuang** [lancerane/Adversarial-domain-adaptation#3]
Thanks you provide this code, but i don't know how to save this weight then test another data
Because this model have three part and i can't use keras save weight, Can u give me some direction?

**Comment by lancerane** [comment]
I'm sorry for not getting back to you. In case this is still causing you problems, you should be able to use:

```
model.save(<FILEPATH>)
```

for each of the three parts separately, then reload each with:

```
model = keras.models.load_model(<FILEPATH>)
```

Hope that helps!

**Comment by lancerane** [comment]
Closing this - hopefully you're problem is now solved
